export const perfisDisponiveis = state => state.perfisDisponiveis;
export const solicitacoes = state => state.solicitacoes;
export const quantidadeSolicitacoes = state => state.quantidadeSolicitacoes;
export const versao = state => state.versao;
export const modoNoturno = state => state.modoNoturno;
export const getStatusSidebarDireita = state => state.statusSidebarDireita;
export const getStatusSidebarEsquerda = state => state.statusSidebarEsquerda;
export const getDadosMenu = state => state.menuPrincipal;
export const getDadosSidebar = state => state.menuSidebar;
